### ISSUE TITLE
Restructure index schema

### ISSUE THREAD

**Issue by johannesdewit** [andredelft/heidegger-index#10]
We want lemmata to contain more information than they do at the moment, like relations between lemmata. In order to maintain a structure we might want to move references into their own key. Related is issue #4 

Example:
```yaml
Anspruch:
  references:
    GA 29/30:
    - start: 429
    - start: 428
  related:
    - Ansprach
  parent: Iets
  reftype:
```

Other ideas for relations: `author` for lemmata with `reftype: w`.
